// Code generated by MockGen. DO NOT EDIT.
// Source: same_mc_restorer.go
//
// Generated by this command:
//
//	mockgen -source=same_mc_restorer.go -package=mock -destination=mock/restorer.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	restorer "github.com/openshift/osdctl/cmd/hcp/restore/internal/restorer"
	gomock "go.uber.org/mock/gomock"
	v1 "open-cluster-management.io/api/work/v1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockClusterContextGetter is a mock of ClusterContextGetter interface.
type MockClusterContextGetter struct {
	ctrl     *gomock.Controller
	recorder *MockClusterContextGetterMockRecorder
	isgomock struct{}
}

// MockClusterContextGetterMockRecorder is the mock recorder for MockClusterContextGetter.
type MockClusterContextGetterMockRecorder struct {
	mock *MockClusterContextGetter
}

// NewMockClusterContextGetter creates a new mock instance.
func NewMockClusterContextGetter(ctrl *gomock.Controller) *MockClusterContextGetter {
	mock := &MockClusterContextGetter{ctrl: ctrl}
	mock.recorder = &MockClusterContextGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterContextGetter) EXPECT() *MockClusterContextGetterMockRecorder {
	return m.recorder
}

// GetClusterContext mocks base method.
func (m *MockClusterContextGetter) GetClusterContext(clusterID string, opts ...restorer.GetClusterContextOption) (*restorer.ClusterContext, error) {
	m.ctrl.T.Helper()
	varargs := []any{clusterID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetClusterContext", varargs...)
	ret0, _ := ret[0].(*restorer.ClusterContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterContext indicates an expected call of GetClusterContext.
func (mr *MockClusterContextGetterMockRecorder) GetClusterContext(clusterID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{clusterID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterContext", reflect.TypeOf((*MockClusterContextGetter)(nil).GetClusterContext), varargs...)
}

// MockGetClusterContextOption is a mock of GetClusterContextOption interface.
type MockGetClusterContextOption struct {
	ctrl     *gomock.Controller
	recorder *MockGetClusterContextOptionMockRecorder
	isgomock struct{}
}

// MockGetClusterContextOptionMockRecorder is the mock recorder for MockGetClusterContextOption.
type MockGetClusterContextOptionMockRecorder struct {
	mock *MockGetClusterContextOption
}

// NewMockGetClusterContextOption creates a new mock instance.
func NewMockGetClusterContextOption(ctrl *gomock.Controller) *MockGetClusterContextOption {
	mock := &MockGetClusterContextOption{ctrl: ctrl}
	mock.recorder = &MockGetClusterContextOptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetClusterContextOption) EXPECT() *MockGetClusterContextOptionMockRecorder {
	return m.recorder
}

// ConfigureGetClusterContext mocks base method.
func (m *MockGetClusterContextOption) ConfigureGetClusterContext(arg0 *restorer.GetClusterContextConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureGetClusterContext", arg0)
}

// ConfigureGetClusterContext indicates an expected call of ConfigureGetClusterContext.
func (mr *MockGetClusterContextOptionMockRecorder) ConfigureGetClusterContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureGetClusterContext", reflect.TypeOf((*MockGetClusterContextOption)(nil).ConfigureGetClusterContext), arg0)
}

// MockMCClient is a mock of MCClient interface.
type MockMCClient struct {
	ctrl     *gomock.Controller
	recorder *MockMCClientMockRecorder
	isgomock struct{}
}

// MockMCClientMockRecorder is the mock recorder for MockMCClient.
type MockMCClientMockRecorder struct {
	mock *MockMCClient
}

// NewMockMCClient creates a new mock instance.
func NewMockMCClient(ctrl *gomock.Controller) *MockMCClient {
	mock := &MockMCClient{ctrl: ctrl}
	mock.recorder = &MockMCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCClient) EXPECT() *MockMCClientMockRecorder {
	return m.recorder
}

// CreateVeleroRestore mocks base method.
func (m *MockMCClient) CreateVeleroRestore(ctx context.Context, backupName, namespace string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVeleroRestore", ctx, backupName, namespace)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVeleroRestore indicates an expected call of CreateVeleroRestore.
func (mr *MockMCClientMockRecorder) CreateVeleroRestore(ctx, backupName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVeleroRestore", reflect.TypeOf((*MockMCClient)(nil).CreateVeleroRestore), ctx, backupName, namespace)
}

// DeleteAllOf mocks base method.
func (m *MockMCClient) DeleteAllOf(ctx context.Context, obj client.Object, opts ...client.DeleteAllOfOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAllOf", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllOf indicates an expected call of DeleteAllOf.
func (mr *MockMCClientMockRecorder) DeleteAllOf(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllOf", reflect.TypeOf((*MockMCClient)(nil).DeleteAllOf), varargs...)
}

// DeleteNamespace mocks base method.
func (m *MockMCClient) DeleteNamespace(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespace", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockMCClientMockRecorder) DeleteNamespace(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespace", reflect.TypeOf((*MockMCClient)(nil).DeleteNamespace), ctx, name)
}

// DeleteVeleroRestore mocks base method.
func (m *MockMCClient) DeleteVeleroRestore(ctx context.Context, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVeleroRestore", ctx, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVeleroRestore indicates an expected call of DeleteVeleroRestore.
func (mr *MockMCClientMockRecorder) DeleteVeleroRestore(ctx, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVeleroRestore", reflect.TypeOf((*MockMCClient)(nil).DeleteVeleroRestore), ctx, name, namespace)
}

// ListResources mocks base method.
func (m *MockMCClient) ListResources(ctx context.Context, list client.ObjectList, filterFn func(client.Object) bool, opts ...client.ListOption) ([]client.Object, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, list, filterFn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResources", varargs...)
	ret0, _ := ret[0].([]client.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockMCClientMockRecorder) ListResources(ctx, list, filterFn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, list, filterFn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockMCClient)(nil).ListResources), varargs...)
}

// ListVeleroRestores mocks base method.
func (m *MockMCClient) ListVeleroRestores(ctx context.Context, clusterID, namespace string) ([]restorer.VeleroRestoreInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVeleroRestores", ctx, clusterID, namespace)
	ret0, _ := ret[0].([]restorer.VeleroRestoreInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVeleroRestores indicates an expected call of ListVeleroRestores.
func (mr *MockMCClientMockRecorder) ListVeleroRestores(ctx, clusterID, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVeleroRestores", reflect.TypeOf((*MockMCClient)(nil).ListVeleroRestores), ctx, clusterID, namespace)
}

// ProbeStatus mocks base method.
func (m *MockMCClient) ProbeStatus(ctx context.Context, list client.ObjectList, probeFn func(client.Object) bool, opts ...restorer.ProbeStatusOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, list, probeFn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProbeStatus", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProbeStatus indicates an expected call of ProbeStatus.
func (mr *MockMCClientMockRecorder) ProbeStatus(ctx, list, probeFn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, list, probeFn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbeStatus", reflect.TypeOf((*MockMCClient)(nil).ProbeStatus), varargs...)
}

// MockProbeStatusOption is a mock of ProbeStatusOption interface.
type MockProbeStatusOption struct {
	ctrl     *gomock.Controller
	recorder *MockProbeStatusOptionMockRecorder
	isgomock struct{}
}

// MockProbeStatusOptionMockRecorder is the mock recorder for MockProbeStatusOption.
type MockProbeStatusOptionMockRecorder struct {
	mock *MockProbeStatusOption
}

// NewMockProbeStatusOption creates a new mock instance.
func NewMockProbeStatusOption(ctrl *gomock.Controller) *MockProbeStatusOption {
	mock := &MockProbeStatusOption{ctrl: ctrl}
	mock.recorder = &MockProbeStatusOptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbeStatusOption) EXPECT() *MockProbeStatusOptionMockRecorder {
	return m.recorder
}

// ConfigureProbeStatus mocks base method.
func (m *MockProbeStatusOption) ConfigureProbeStatus(arg0 *restorer.ProbeStatusConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureProbeStatus", arg0)
}

// ConfigureProbeStatus indicates an expected call of ConfigureProbeStatus.
func (mr *MockProbeStatusOptionMockRecorder) ConfigureProbeStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureProbeStatus", reflect.TypeOf((*MockProbeStatusOption)(nil).ConfigureProbeStatus), arg0)
}

// MockSCClient is a mock of SCClient interface.
type MockSCClient struct {
	ctrl     *gomock.Controller
	recorder *MockSCClientMockRecorder
	isgomock struct{}
}

// MockSCClientMockRecorder is the mock recorder for MockSCClient.
type MockSCClientMockRecorder struct {
	mock *MockSCClient
}

// NewMockSCClient creates a new mock instance.
func NewMockSCClient(ctrl *gomock.Controller) *MockSCClient {
	mock := &MockSCClient{ctrl: ctrl}
	mock.recorder = &MockSCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSCClient) EXPECT() *MockSCClientMockRecorder {
	return m.recorder
}

// GetManifestWork mocks base method.
func (m *MockSCClient) GetManifestWork(ctx context.Context, name string) (*v1.ManifestWork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManifestWork", ctx, name)
	ret0, _ := ret[0].(*v1.ManifestWork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManifestWork indicates an expected call of GetManifestWork.
func (mr *MockSCClientMockRecorder) GetManifestWork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManifestWork", reflect.TypeOf((*MockSCClient)(nil).GetManifestWork), ctx, name)
}

// UpdateManifestWork mocks base method.
func (m *MockSCClient) UpdateManifestWork(ctx context.Context, mw *v1.ManifestWork) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateManifestWork", ctx, mw)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateManifestWork indicates an expected call of UpdateManifestWork.
func (mr *MockSCClientMockRecorder) UpdateManifestWork(ctx, mw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateManifestWork", reflect.TypeOf((*MockSCClient)(nil).UpdateManifestWork), ctx, mw)
}

// MockSameMCRestorerOption is a mock of SameMCRestorerOption interface.
type MockSameMCRestorerOption struct {
	ctrl     *gomock.Controller
	recorder *MockSameMCRestorerOptionMockRecorder
	isgomock struct{}
}

// MockSameMCRestorerOptionMockRecorder is the mock recorder for MockSameMCRestorerOption.
type MockSameMCRestorerOptionMockRecorder struct {
	mock *MockSameMCRestorerOption
}

// NewMockSameMCRestorerOption creates a new mock instance.
func NewMockSameMCRestorerOption(ctrl *gomock.Controller) *MockSameMCRestorerOption {
	mock := &MockSameMCRestorerOption{ctrl: ctrl}
	mock.recorder = &MockSameMCRestorerOptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSameMCRestorerOption) EXPECT() *MockSameMCRestorerOptionMockRecorder {
	return m.recorder
}

// ConfigureSameMCRestorer mocks base method.
func (m *MockSameMCRestorerOption) ConfigureSameMCRestorer(arg0 *restorer.SameMCRestorerConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureSameMCRestorer", arg0)
}

// ConfigureSameMCRestorer indicates an expected call of ConfigureSameMCRestorer.
func (mr *MockSameMCRestorerOptionMockRecorder) ConfigureSameMCRestorer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureSameMCRestorer", reflect.TypeOf((*MockSameMCRestorerOption)(nil).ConfigureSameMCRestorer), arg0)
}
